version: '3.8'

services:
  flask:
    build:
      context: ./app  # Caminho para a pasta onde está o Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - chrome
    environment:
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
    volumes:
      - ./app:/app  # Mapeia o diretório local `app` para `/app` no contêiner

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
